AppBancoLM/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;

namespace AppBancoLM.Models
{
    public class Cliente
    {
        [Display(Name = "Código")]
        public int? IdCli { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]
        public string nomeCli { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "O email não é valido.")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email valido...")]
        public string Email { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]
        public DateTime DataNasc { get; set; }

        [Display(Name = "Sexo")]
        [Required(ErrorMessage = "O sexo é obrigatório.")]
        [StringLength(1, ErrorMessage = "Deve conter 1 caracter.")]
        public string Sexo { get; set; }
    }
}

AppBancoLM/Models/ErrorViewModel.cs
namespace AppBancoLM.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppBancoLM/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace AppBancoLM.Models
{
    public class Usuario
    {
        [Display(Name = "Código")]
        public int? IdUsu { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]
        public string nomeUsua { get; set; }

        [Display(Name = "Cargo")]
        [Required(ErrorMessage = "O campo cargo é obrigatório")]
        public string Cargo { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]

        public DateTime DataNasc { get; set; }

    }
}

AppBancoLM/Controllers/ClienteController.cs
using AppBancoLM.Models;
using AppBancoLM.Repository;
using AppBancoLM.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppBancoLM.Controllers
{
    public class ClienteController : Controller
    {
    
            private IClienteRepository _clienteRepository;
            public ClienteController(IClienteRepository clienteRepository)
            {
                _clienteRepository = clienteRepository;
            }
            public IActionResult Index()
            {
                return View(_clienteRepository.ObterTodosClientes());
            }
            [HttpGet]
            public IActionResult CadastrarCliente()
            {
                return View();
            }
            [HttpPost]
            public IActionResult CadastrarCliente(Cliente cliente)
            {
                if (ModelState.IsValid)
                {
                    _clienteRepository.Cadastrar(cliente);
                }
                return View();
            }
            [HttpGet]
            public IActionResult AtualizarCliente(int id)
            {
                return View(_clienteRepository.ObterCliente(id));
            }
            [HttpPost]
            public IActionResult AtualizarCliente(Cliente cliente)
            {
                _clienteRepository.Atualizar(cliente);

                return RedirectToAction(nameof(Index));
            }
            [HttpGet]
            public IActionResult DetalhesCliente(int id)
            {
                return View(_clienteRepository.ObterCliente(id));
            }
            [HttpPost]
            public IActionResult DetalhesCliente(Cliente cliente)
            {
                _clienteRepository.Atualizar(cliente);

                return RedirectToAction(nameof(Index));
            }
            public IActionResult ExcluirCliente(int id)
            {
                _clienteRepository.Excluir(id);
                return RedirectToAction(nameof(Index));
            }
        
    }



    /*

    public IActionResult AtualizarCliente(int id)
    {
        return View(_clienteRepository.ObterCliente(id));
    }
    [HttpPost]
    public IActionResult AtualizarCliente(Cliente cliente)
    {
        _clienteRepository.Atualizar(cliente);

        return RedirectToAction(nameof(Index));
    }
    [HttpGet]
    public IActionResult DetalhesCliente(int id)
    {
        return View(_clienteRepository.ObterCliente(id));
    }
    [HttpPost]
    public IActionResult DetalhesCliente(Cliente cliente)
    {
        _clienteRepository.Atualizar(cliente);

        return RedirectToAction(nameof(Index));
    }
    public IActionResult ExcluirCliente(int id)
    {
        _clienteRepository.Excluir(id);
        return RedirectToAction(nameof(Index));
    }



    private IClienteRepository _clienteRepository;

    public ClienteController(IClienteRepository clienteRepository)
    {
        _clienteRepository = clienteRepository;
    }

    [HttpGet]
    public IActionResult CadastrarCliente()
    {
        return View();
    }

    [HttpPost]

    public IActionResult CadastrarCliente(Cliente cliente)
    {
        if (ModelState.IsValid)
        {
            _clienteRepository.Cadastrar(cliente);
        }
        return View();
    }
    [HttpGet]


    public IActionResult Index()
    {
        return View();
    }
    */


}

AppBancoLM/Controllers/HomeController.cs
using AppBancoLM.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppBancoLM.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //teste
    }
}

AppBancoLM/Controllers/UsuarioController.cs
using AppBancoLM.Models;
using AppBancoLM.Repository;
using AppBancoLM.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppBancoLM.Controllers
{
    public class UsuarioController : Controller
    {
        private IUsuarioRepository _usuarioRepository;

        public UsuarioController (IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }
        public IActionResult Index()
        {
            return View(_usuarioRepository.ObterTodosUsuarios());
        }
        [HttpGet]
        public IActionResult CadastrarUsuario()
        {
            return View();
        }
        
        [HttpPost]

        public IActionResult CadastrarUsuario(Usuario usuario)
        {
            if(ModelState.IsValid)
            {
                _usuarioRepository.Cadastrar(usuario);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AtualizarUsuario(int id)
        {
            return View(_usuarioRepository.ObterUsuario(id));
        }
        [HttpPost]
        public IActionResult AtualizarUsuario(Usuario usuario)
        {
            _usuarioRepository.Atualizar(usuario);

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DetalhesUsuario(int id)
        {
            return View(_usuarioRepository.ObterUsuario(id));
        }
        [HttpPost]
        public IActionResult DetalhesUsuario(Usuario usuario)
        {
            _usuarioRepository.Atualizar(usuario);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExcluirUsuario(int id)
        {
            _usuarioRepository.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

    }

}

AppBancoLM/Views/Cliente/AtualizarCliente.cshtml
@model AppBancoLM.Models.Cliente

@{
    ViewData["Title"] = "AtualizarCliente";
}

<h1>AtualizarCliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomeCli" class="control-label"></label>
                <input asp-for="nomeCli" class="form-control" />
                <span asp-validation-for="nomeCli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppBancoLM/Views/Cliente/CadastrarCliente.cshtml
@model AppBancoLM.Models.Cliente

@{
    ViewData["Title"] = "CadastrarCliente";
}

<h1>Cadastrar Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="nomeCli" class="control-label"></label>
                <input asp-for="nomeCli" class="form-control" />
                <span asp-validation-for="nomeCli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppBancoLM/Views/Cliente/DetalhesCliente.cshtml
@model AppBancoLM.Models.Cliente

@{
    ViewData["Title"] = "DetalhesCliente";
}

<h1>DetalhesCliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nomeCli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nomeCli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNasc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AppBancoLM/Views/Cliente/ExcluirCliente.cshtml
@model AppBancoLM.Models.Cliente

@{
    ViewData["Title"] = "ExcluirCliente";
}

<h1>ExcluirCliente</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nomeCli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nomeCli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNasc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
    </dl>
    
    <form asp-action="ExcluirCliente">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppBancoLM/Views/Cliente/Index.cshtml
@model IEnumerable<AppBancoLM.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Cliente" asp-action="CadastrarCliente">Cadastrar novo cliente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCli)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nomeCli)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNasc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCli)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nomeCli)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNasc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                    <button type="button" class="btn btn-warning">
                        @Html.ActionLink("Editar", "AtualizarCliente", new { /* id=item.PrimaryKey */ })
                    </button>|
                    <button type="button" class="btn btn-secondary">
                        @Html.ActionLink("Detalhes", "DetalhesCliente", new { /* id=item.PrimaryKey */ })
                    </button>|
                    <button type="button" class="btn btn-danger">
                        @Html.ActionLink("Deletar", "ExcluirCliente", new { /* id=item.PrimaryKey */ })
                    </button>
            </td>
        </tr>
}
    </tbody>
</table>

AppBancoLM/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppBancoLM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppBancoLM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppBancoLM.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppBancoLM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CadastrarUsuario">Cadastrar usuário</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="CadastrarCliente">Cadastrar cliente</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppBancoLM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppBancoLM/Views/Usuario/AtualizarUsuario.cshtml
@model AppBancoLM.Models.Usuario

@{
    ViewData["Title"] = "AtualizarUsuario";
}

<h1>Atualizar Usuario</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarUsuario">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomeUsua" class="control-label"></label>
                <input asp-for="nomeUsua" class="form-control" />
                <span asp-validation-for="nomeUsua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AppBancoLM/Views/Usuario/CadastrarUsuario.cshtml
@model AppBancoLM.Models.Usuario

@{
    ViewData["Title"] = "CadastrarUsuario";
}

<h1>CadastrarUsuario</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarUsuario">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomeUsua" class="control-label"></label>
                <input asp-for="nomeUsua" class="form-control" />
                <span asp-validation-for="nomeUsua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input type="date" asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppBancoLM/Views/Usuario/DetalhesUsuario.cshtml
@model AppBancoLM.Models.Usuario

@{
    ViewData["Title"] = "DetalhesUsuario";
}

<h1>Detalhes Usuario</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nomeUsua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nomeUsua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNasc)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "AtualizarUsuario", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AppBancoLM/Views/Usuario/ExcluirUsuario.cshtml
@model AppBancoLM.Models.Usuario

@{
    ViewData["Title"] = "Excluir Usuario";
}

<h1>Excluir Usuario</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nomeUsua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nomeUsua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNasc)
        </dd>
    </dl>
    
    <form asp-action="ExcluirUsuario">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppBancoLM/Views/Usuario/Index.cshtml
@model IEnumerable<AppBancoLM.Models.Usuario>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdUsu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nomeUsua)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cargo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNasc)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nomeUsua)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNasc)
            </td>
            <td>
                <button type="button" class="btn btn-warning">
                @Html.ActionLink("Editar", "AtualizarUsuario", new { /* id=item.PrimaryKey */ })
                </button>|
                <button type="button" class="btn btn-secondary">
                        @Html.ActionLink("Detalhes", "DetalhesUsuario", new { /* id=item.PrimaryKey */ })
                </button>|
                <button type="button" class="btn btn-danger">
                @Html.ActionLink("Deletar", "ExcluirUsuario", new { /* id=item.PrimaryKey */ })
                </button>
            </td>
        </tr>
}
    </tbody>
</table>